added the same render prop for the old interface
trufflesuite/drizzle-react-components pull request #95
Opened 2019-03-27 15:23 UTC by mwaeckerlin

@honestbonsai, please accept my addition to your implementation and pull it back to the develop branch.

2019-03-27 19:48 UTC, mwaeckerlin commented
This will solve #86 and replaces #89

2019-03-28 15:01 UTC, honestbonsai requested changes

2019-03-28 15:01 UTC, honestbonsai commented on src/ContractForm.js
> +  render: PropTypes.function,
It's `PropTypes.func` https://reactjs.org/docs/typechecking-with-proptypes.html

2019-03-28 15:31 UTC, mwaeckerlin commented on src/ContractForm.js
> +  render: PropTypes.function,
upps sorry, written from my mind instead of double checking…

@honestbonsai, could you recheck now, please?

2019-03-28 16:55 UTC, merged